---
### postgresql ###
# postgresql_version: 9.6
# postgresql_user: root
# postgresql_password: root
# postgresql_database: "{{ application_name }}"
# postgresql_port: 5432:5432
# postgresql_data_home: "{{ data_home }}/postgresql"

### mysql ###
# mysql_version: 5.6
# mysql_root_password: root
# mysql_database: "{{ application_name }}"
# mysql_port: 3306:3306
# mysql_configuration_home: "{{ configuration_home }}/mysql"
# mysql_data_home: "{{ data_home }}/mysql"

### mariadb ###
# mariadb_version: 10.1.18
# mariadb_root_password: root
# mariadb_database: "{{ application_name }}"
# mariadb_port: 3306:3306
# mariadb_configuration_home: "{{ configuration_home }}/mariadb"
# mariadb_data_home: "{{ data_home }}/mariadb"

### mongodb ###
# mongodb_version: 3.3
# mongodb_port: 27017:27017
# mongodb_data_home: "{{ data_home }}/mongodb"

### redis ###
redis_version: 3.2.4
redis_port: 6379:6379
redis_configuration_home: "{{ configuration_home }}/redis"
redis_data_home: "{{ data_home }}/redis"

### rabbitmq ###
# rabbitmq_version: 3
# rabbitmq_user: root
# rabbitmq_password: root
# rabbitmq_node_name:  "{{ application_name }}@rabbit"
# rabbitmq_cookie:  "{{ application_name }}_rabbit_cookie"
# rabbitmq_ports: 
#   - 5672:5672
#   - 15672:15672
# rabbitmq_data_home: "{{ data_home }}/rabbitmq"